"""initial_schema

Revision ID: 1353f612220a
Revises:
Create Date: 2026-04-13 09:55:12.093666

"""

# revision identifiers, used by Alembic.
revision = "1353f612220a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
