"""Added AI quota metrics

Revision ID: 92d5df230aad
Revises: 1353f612220a
Create Date: 2026-04-13 11:56:58.876916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d5df230aad'
down_revision = '1353f612220a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('completion_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('ip_address')
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('completion_tokens')
        batch_op.drop_column('prompt_tokens')

    # ### end Alembic commands ###
